export type PageTemplateType =
  | "HOMEPAGE"
  | "CATEGORY"
  | "PRODUCT"
  | "VENDOR_STORE"
  | "BLOG"
  | "LANDING"
  | "CAMPAIGN"
  | "CUSTOM";

export interface PageTemplateItem {
  id: string;
  name: string;
  slug: string;
  type: PageTemplateType;
  description: string;
  thumbnail: string;
  isDefault: boolean;
  sections: any[];
  styling?: any;
}

export const BUILTIN_PAGE_TEMPLATES: PageTemplateItem[] = [
  {
    id: "tpl_homepage_default",
    name: "Classic Marketplace Homepage",
    slug: "homepage-template",
    type: "HOMEPAGE",
    description: "Multi-vendor hero slider, category avatar reel, ticking flash deals, bestseller showcase, artisan spotlight, and newsletter.",
    thumbnail: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80",
    isDefault: true,
    sections: [
      {
        type: "HERO_BANNER",
        name: "Festival Grand Hero Slider",
        title: "Authentic Indian Crafts & Modern Electronics",
        subtitle: "Direct from master weavers in Surat, Varanasi & top verified sellers",
        settings: {
          title: "Diwali & Festive Mega Heritage Festival",
          subtitle: "Up to 60% OFF on Banarasi Silk, Linen Kurtas & ANC Earbuds",
          ctaText: "Explore Festive Collection",
          ctaLink: "/deals",
          badge: "FESTIVE 2026 LIVE",
        },
        style: { paddingY: "py-4", backgroundColor: "#0F172A" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "CATEGORY_CAROUSEL",
        name: "Top Categories Carousel",
        title: "Shop by Department",
        subtitle: "Explore 75+ authentic Indian departments",
        settings: { limit: 8 },
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "CATEGORIES", limit: 8, parentId: "root" },
      },
      {
        type: "FLASH_DEALS",
        name: "Urgent Flash Deals",
        title: "Ticking Flash Sale — Flat 50% OFF",
        subtitle: "Limited quantity deals expiring soon",
        settings: { hoursRemaining: 14, badge: "⚡ FLAT 50% OFF" },
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "PRODUCTS", sourceType: "discounted", limit: 4 },
      },
      {
        type: "PRODUCT_GRID",
        name: "Handpicked Trending Products",
        title: "Trending in India Right Now",
        subtitle: "Most loved handloom and electronics items this week",
        settings: { showViewAll: true, viewAllUrl: "/shop" },
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "PRODUCTS", sourceType: "trending", limit: 8 },
      },
      {
        type: "TOP_VENDORS",
        name: "Verified Master Artisans",
        title: "Meet India's Master Weavers & Guilds",
        subtitle: "Direct-to-consumer certified handicraft studios",
        settings: { limit: 3 },
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "VENDORS", limit: 3 },
      },
      {
        type: "TRUST_BADGES",
        name: "Marketplace Assurance Strip",
        title: "Why Shop with FancyHub?",
        subtitle: "Guaranteed authentic artisan goods with 100% buyer protection",
        settings: {},
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "NEWSLETTER",
        name: "Instant Discount Newsletter",
        title: "Unlock Instant ₹500 Welcome Discount",
        subtitle: "Subscribe for private vault drops, loom stories, and weekend vouchers.",
        settings: { couponCode: "WELCOME500" },
        style: { paddingY: "py-8", backgroundColor: "#0F172A" },
        dataSource: { type: "STATIC" },
      },
    ],
  },

  {
    id: "tpl_category_default",
    name: "Department & Category Template",
    slug: "category-template",
    type: "CATEGORY",
    description: "Category hero header, subcategory chips, product filter grid, customer reviews, and FAQ accordion.",
    thumbnail: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80",
    isDefault: true,
    sections: [
      {
        type: "HEADING",
        name: "Category Department Header",
        title: "Department Showcase",
        subtitle: "Browse handcrafted styles with direct maker pricing",
        settings: { title: "Explore Full Collection", subtitle: "Curated Indian weaves and high-performance essentials" },
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "CATEGORY_GRID",
        name: "Subcategory Directory",
        title: "Subcategories",
        subtitle: "Pick a specific department",
        settings: { limit: 6 },
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "CATEGORIES", limit: 6 },
      },
      {
        type: "PRODUCT_GRID",
        name: "Category Products Filtered",
        title: "All Products in Department",
        subtitle: "Showing latest stock updated in real time",
        settings: { showViewAll: false },
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "PRODUCTS", sourceType: "latest", limit: 12 },
      },
      {
        type: "FAQ",
        name: "Category Frequently Asked Questions",
        title: "Frequently Asked Questions",
        subtitle: "Everything you need to know about shipping, authenticity and sizing",
        settings: {},
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
    ],
  },

  {
    id: "tpl_product_default",
    name: "Product Detail Showcase Template",
    slug: "product-template",
    type: "PRODUCT",
    description: "Product spotlight, artisan background story, customer reviews, similar recommendations, and trust warranty.",
    thumbnail: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
    isDefault: true,
    sections: [
      {
        type: "PRODUCT_CARD",
        name: "Featured Spotlight Product",
        title: "Featured Artisan Creation",
        subtitle: "Handcrafted with pure silk threads and organic natural dyes",
        settings: {},
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "PRODUCTS", sourceType: "featured", limit: 1 },
      },
      {
        type: "RECOMMENDED_PRODUCTS",
        name: "Similar Style Recommendations",
        title: "You May Also Love",
        subtitle: "Recommended based on your current selection",
        settings: {},
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "PRODUCTS", sourceType: "trending", limit: 4 },
      },
      {
        type: "TESTIMONIALS",
        name: "Verified Customer Reviews",
        title: "Loved by Over 50,000+ Patrons",
        subtitle: "Read authentic feedback from verified Indian buyers",
        settings: {},
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "SECURE_PAYMENTS",
        name: "Security & Warranty Badges",
        title: "Guaranteed Safe Shopping",
        subtitle: "All orders covered under FancyHub Buyer Shield",
        settings: {},
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
    ],
  },

  {
    id: "tpl_vendor_store_default",
    name: "Vendor Artisan Storefront Template",
    slug: "vendor-store-template",
    type: "VENDOR_STORE",
    description: "Vendor hero banner, weaver background biography, verified seller certificate, full store catalog, and seller reviews.",
    thumbnail: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80",
    isDefault: true,
    sections: [
      {
        type: "VENDOR_STORE_CARD",
        name: "Vendor Profile Header",
        title: "Master Weaver Studio",
        subtitle: "4th generation traditional handloom heritage weavers from Surat",
        settings: {},
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "VENDORS", limit: 1 },
      },
      {
        type: "VENDOR_PRODUCTS",
        name: "Vendor Full Catalog",
        title: "Store Catalog",
        subtitle: "All products shipped directly from this workshop",
        settings: { showViewAll: false },
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "PRODUCTS", sourceType: "vendor", limit: 8 },
      },
      {
        type: "TRUSTED_VENDORS",
        name: "Authenticity Verification",
        title: "Government Handloom Mark Verified",
        subtitle: "100% silk purity and lab tested materials",
        settings: {},
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
    ],
  },

  {
    id: "tpl_blog_default",
    name: "Editorial & Loom Stories Blog Template",
    slug: "blog-template",
    type: "BLOG",
    description: "Artisan magazine hero, rich storytelling columns, cultural heritage essays, and newsletter subscription.",
    thumbnail: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&auto=format&fit=crop&q=80",
    isDefault: true,
    sections: [
      {
        type: "HEADING",
        name: "Blog Header Title",
        title: "Stories from the Indian Loom",
        subtitle: "Essays on traditional textile heritage, master crafts, and modern Indian innovation.",
        settings: { title: "The Artisan Journal", subtitle: "Preserving India's 5,000-year textile heritage" },
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "BLOG_POSTS",
        name: "Recent Editorial Stories",
        title: "Latest Heritage Dispatches",
        subtitle: "Direct reports from weaving clusters across India",
        settings: { limit: 3 },
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "RICH_TEXT",
        name: "Featured Weaver Interview",
        title: "Behind the Loom: The Master of Varanasi",
        subtitle: "How pure mulberry silk transforms into timeless heirloom sarees",
        settings: {},
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "NEWSLETTER",
        name: "Journal Subscription Box",
        title: "Subscribe to The Artisan Journal",
        subtitle: "Weekly stories, weaver profiles, and exclusive collector previews in your inbox.",
        settings: { couponCode: "JOURNAL10" },
        style: { paddingY: "py-8", backgroundColor: "#0F172A" },
        dataSource: { type: "STATIC" },
      },
    ],
  },

  {
    id: "tpl_landing_default",
    name: "High-Conversion Landing Page Template",
    slug: "landing-page-template",
    type: "LANDING",
    description: "High-impact CTA hero, value propositions, key benefit cards, featured offer countdown, social proof, and closing button.",
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80",
    isDefault: true,
    sections: [
      {
        type: "HERO_BANNER",
        name: "High Impact Landing Hero",
        title: "Experience India's Finest Weaves",
        subtitle: "Direct from the artisan looms with zero middleman markups",
        settings: {
          title: "Direct from Artisan Looms",
          subtitle: "Save 40% on certified pure silk & linen apparel",
          ctaText: "Shop The Collection",
          ctaLink: "/shop",
        },
        style: { paddingY: "py-8", backgroundColor: "#0F172A" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "FAST_DELIVERY",
        name: "Value Pillars",
        title: "Express 24-48h Dispatch",
        subtitle: "Fast doorstep delivery across 26,000+ Indian pincodes",
        settings: {},
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "FEATURED_PRODUCTS",
        name: "Hero Showcase Grid",
        title: "Our Signature Selections",
        subtitle: "The most requested handcrafted items",
        settings: {},
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "PRODUCTS", sourceType: "featured", limit: 4 },
      },
      {
        type: "CTA_BANNER",
        name: "Bottom Conversion Ribbon",
        title: "Ready to Upgrade Your Wardrobe?",
        subtitle: "Get FLAT ₹500 OFF on your first purchase today with code FANCYFIRST.",
        settings: {
          buttonText: "Claim ₹500 Discount",
          buttonLink: "/register",
        },
        style: { paddingY: "py-8", backgroundColor: "#1455D9" },
        dataSource: { type: "STATIC" },
      },
    ],
  },

  {
    id: "tpl_campaign_default",
    name: "Festive Campaign & Flash Sale Template",
    slug: "campaign-template",
    type: "CAMPAIGN",
    description: "Festive festival banner, countdown clock, coupon vouchers strip, steep markdown deals, and partner logos.",
    thumbnail: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&auto=format&fit=crop&q=80",
    isDefault: true,
    sections: [
      {
        type: "FESTIVAL_BANNER",
        name: "Diwali / Wedding Season Banner",
        title: "The Grand Indian Festive Celebration",
        subtitle: "Celebrate with handwoven heritage and exclusive festive vouchers",
        settings: {
          badge: "FESTIVE SPECIAL 2026",
          title: "Diwali & Wedding Season Super Sale",
          subtitle: "Extra 20% OFF via UPI & Instant Cashback",
        },
        style: { paddingY: "py-8", backgroundColor: "#3B0764" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "COUNTDOWN_TIMER",
        name: "Campaign Urgency Clock",
        title: "Sale Ends In",
        subtitle: "Grab limited edition festive stock before prices increase",
        settings: { days: 2, hours: 14, minutes: 30 },
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "COUPON_BANNER",
        name: "Claimable Discount Vouchers",
        title: "Exclusive Campaign Coupons",
        subtitle: "Click any coupon code below to copy instantly to your clipboard",
        settings: {},
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
      {
        type: "FLASH_DEALS",
        name: "Festive Flash Sale Showcase",
        title: "Lightning Deals — Flat 50% OFF",
        subtitle: "Heavily discounted handloom weaves and smart electronics",
        settings: { hoursRemaining: 12 },
        style: { paddingY: "py-6", backgroundColor: "transparent" },
        dataSource: { type: "PRODUCTS", sourceType: "discounted", limit: 4 },
      },
      {
        type: "BRAND_LOGOS",
        name: "Partner Brands Marquee",
        title: "Official Guild Partners",
        subtitle: "Certified partner brands & weaving federations",
        settings: {},
        style: { paddingY: "py-4", backgroundColor: "transparent" },
        dataSource: { type: "STATIC" },
      },
    ],
  },
];
