/**
 * FancyHub.in — Centralized Global Route Architecture
 * Every link and button across Customer, Vendor, Admin, and Auth routes
 * must use these centralized constants.
 */

export const ROUTES = {
  // Customer Marketplace
  home: "/",
  shop: "/shop",
  categories: "/categories",
  category: (slug: string, parentSlug?: string) =>
    parentSlug ? `/category/${parentSlug}/${slug}` : `/category/${slug}`,
  product: (slug: string) => `/product/${slug}`,
  products: "/products",
  search: (query?: string, category?: string) => {
    const params = new URLSearchParams();
    if (query) params.set("q", query);
    if (category && category !== "all") params.set("cat", category);
    const queryString = params.toString();
    return queryString ? `/search?${queryString}` : "/search";
  },
  deals: "/deals",
  offers: "/offers",
  flashSale: "/flash-sale",
  newArrivals: "/new-arrivals",
  bestSellers: "/best-sellers",
  brands: "/brands",
  brand: (slug: string) => `/brand/${slug}`,
  vendors: "/vendors",
  vendor: (slug: string) => `/vendor/${slug}`,
  customPrint: "/custom-print",
  cart: "/cart",
  checkout: "/checkout",
  orderSuccess: (id?: string) => (id ? `/order-success/${id}` : "/order-success"),
  orders: "/orders",
  orderDetail: (id: string) => `/orders/${id}`,
  trackOrder: "/track-order",
  wishlist: "/wishlist",
  compare: "/compare",
  wallet: "/wallet",
  coupons: "/coupons",
  notifications: "/notifications",
  messages: "/messages",
  help: "/help",
  customPage: (slug: string) => `/p/${slug}`,
  blog: (slug?: string) => (slug ? `/blog/${slug}` : "/blog"),

  // Customer Account
  account: {
    dashboard: "/account",
    profile: "/account/profile",
    orders: "/account/orders",
    addresses: "/account/addresses",
    wishlist: "/account/wishlist",
    reviews: "/account/reviews",
    returns: "/account/returns",
    wallet: "/account/wallet",
    coupons: "/account/coupons",
    security: "/account/security",
    settings: "/account/settings",
  },

  // Tags
  tag: (slug: string) => `/tag/${slug}`,

  // Authentication
  auth: {
    login: "/login",
    register: "/register",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    verifyEmail: "/verify-email",
    verifyPhone: "/verify-phone",
  },

  // Vendor Portal
  vendorPortal: {
    login: "/vendor/login",
    register: "/vendor/register",
    dashboard: "/vendor/dashboard",
    products: "/vendor/products",
    newProduct: "/vendor/products/new",
    editProduct: (id: string) => `/vendor/products/${id}/edit`,
    orders: "/vendor/orders",
    orderDetail: (id: string) => `/vendor/orders/${id}`,
    coupons: "/vendor/coupons",
    analytics: "/vendor/analytics",
    customers: "/vendor/customers",
    reviews: "/vendor/reviews",
    withdraw: "/vendor/withdraw",
    wallet: "/vendor/wallet",
    shipping: "/vendor/shipping",
    store: "/vendor/store",
    storeSettings: "/vendor/store/settings",
    storeSeo: "/vendor/store/seo",
    staff: "/vendor/staff",
    messages: "/vendor/messages",
    announcements: "/vendor/announcements",
    support: "/vendor/support",
  },

  // Admin ERP Console
  admin: {
    login: "/admin/login",
    dashboard: "/admin/dashboard",
    vendors: "/admin/vendors",
    vendorDetail: (id: string) => `/admin/vendors/${id}`,
    products: "/admin/products",
    categories: "/admin/categories",
    brands: "/admin/brands",
    tags: "/admin/tags",
    orders: "/admin/orders",
    customers: "/admin/customers",
    payments: "/admin/payments",
    commissions: "/admin/commissions",
    payouts: "/admin/payouts",
    coupons: "/admin/coupons",
    reviews: "/admin/reviews",
    returns: "/admin/returns",
    refunds: "/admin/refunds",
    disputes: "/admin/disputes",
    support: "/admin/support",
    returnPolicies: "/admin/return-policies",
    shipping: "/admin/shipping",
    banners: "/admin/banners",
    homepage: "/admin/homepage",
    visualBuilder: "/admin/visual-builder",
    productBuilder: "/admin/product-builder",
    categoryBuilder: "/admin/category-builder",
    headerBuilder: "/admin/header-builder",
    footerBuilder: "/admin/footer-builder",
    navigation: "/admin/navigation",
    pages: "/admin/pages",
    themeStudio: "/admin/theme-studio",
    websiteControl: "/admin/website-control",
    media: "/admin/media",
    widgetMarketplace: "/admin/widget-marketplace",
    floatingWidgets: "/admin/floating-widgets",
    sections: "/admin/reusable-blocks",
    reusableBlocks: "/admin/reusable-blocks",
    popups: "/admin/popups",
    campaigns: "/admin/campaigns",
    marketing: "/admin/campaigns",
    menus: "/admin/menus",
    seo: "/admin/seo",
    redirects: "/admin/redirects",
    themeVersions: "/admin/theme-versions",
    scheduledChanges: "/admin/scheduled-changes",
    brandControl: "/admin/brand-control",
    checkoutDesigner: "/admin/checkout-designer",
    accountDesigner: "/admin/account-designer",
    emptyStates: "/admin/empty-states",
    maintenance: "/admin/maintenance",
    users: "/admin/users",
    roles: "/admin/roles",
    notifications: "/admin/notifications",
    plans: "/admin/plans",
    settings: "/admin/settings",
    auditLogs: "/admin/audit-logs",
    reports: "/admin/reports",
    security: "/admin/security",
    integrations: "/admin/integrations",
    apiManagement: "/admin/integrations",
    workflows: "/admin/workflows",
    automations: "/admin/workflows",
  },
  page: (slug: string) => `/p/${slug}`,
};
