import { WidgetDefinition, WidgetType, WidgetCategory } from "./widget-types";

export const WIDGET_CATEGORIES: { id: WidgetCategory; name: string; icon: string }[] = [
  { id: "content", name: "Content & Typography", icon: "Type" },
  { id: "ecommerce", name: "E-commerce & Products", icon: "ShoppingCart" },
  { id: "category", name: "Category Navigation", icon: "Grid" },
  { id: "vendor", name: "Vendor & Sellers", icon: "Store" },
  { id: "marketing", name: "Marketing & Conversion", icon: "Zap" },
  { id: "trust", name: "Trust & Assurance", icon: "ShieldCheck" },
  { id: "social", name: "Social & Reviews", icon: "MessageSquare" },
  { id: "utility", name: "Utility & Navigation", icon: "Sliders" },
];

export const WIDGET_REGISTRY: Record<WidgetType, WidgetDefinition> = {
  // ==========================================
  // 1. CONTENT WIDGETS (8)
  // ==========================================
  TEXT: {
    type: "TEXT",
    name: "Text Paragraph",
    category: "content",
    categoryName: "Content & Typography",
    description: "Custom styled text paragraph with font size & alignment controls",
    iconName: "FileText",
    defaultSettings: {
      text: "Discover handloom treasures, contemporary fashion, and authentic Indian innovations with direct artisan pricing and doorstep pan-India delivery.",
      fontSize: "text-sm",
      alignment: "left",
      lineHeight: "leading-relaxed",
    },
    defaultStyle: { paddingY: "py-2", textColor: "#475569" },
    defaultResponsive: { desktop: { alignment: "left" }, mobile: { alignment: "center" } },
    defaultDataSource: { type: "STATIC" },
  },
  HEADING: {
    type: "HEADING",
    name: "Section Heading",
    category: "content",
    categoryName: "Content & Typography",
    description: "Configurable heading title (H1–H6) with subtitle, gradient effect & badge",
    iconName: "Heading",
    defaultSettings: {
      title: "Featured Indian Collections",
      subtitle: "Handcrafted with passion by master weavers across Surat, Varanasi & Kanchipuram",
      tag: "H2",
      badgeText: "PREMIUM",
      useGradient: true,
      alignment: "left",
    },
    defaultStyle: { paddingY: "py-3" },
    defaultResponsive: { desktop: { alignment: "left" }, mobile: { alignment: "center" } },
    defaultDataSource: { type: "STATIC" },
  },
  RICH_TEXT: {
    type: "RICH_TEXT",
    name: "Rich Text Editorial",
    category: "content",
    categoryName: "Content & Typography",
    description: "Multi-column rich text formatted story, artisan biography, or platform manifesto",
    iconName: "BookOpen",
    defaultSettings: {
      heading: "The FancyHub Heritage Story",
      bodyHtml: "<p>FancyHub connects over <strong>5,000+ certified master weavers</strong> directly to discerning Indian shoppers. Eliminating middlemen ensures authentic craftsmanship and 40-60% genuine cost savings.</p>",
      columns: 1,
    },
    defaultStyle: { paddingY: "py-4", backgroundColor: "transparent" },
    defaultResponsive: { desktop: { columns: 1 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "STATIC" },
  },
  IMAGE: {
    type: "IMAGE",
    name: "Image Showcase",
    category: "content",
    categoryName: "Content & Typography",
    description: "Single responsive banner image with optional lightbox, caption, and clickable link",
    iconName: "Image",
    defaultSettings: {
      imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&auto=format&fit=crop&q=80",
      altText: "Handloom Banarasi Saree Weaving",
      caption: "Authentic Zari Silk Handcrafted in Varanasi",
      aspectRatio: "16/9",
      targetUrl: "/shop",
      borderRadius: "rounded-3xl",
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { paddingY: "py-4" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  VIDEO: {
    type: "VIDEO",
    name: "Video Player",
    category: "content",
    categoryName: "Content & Typography",
    description: "Embedded video reel showcasing weaver workshops or product teasers",
    iconName: "Video",
    defaultSettings: {
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      title: "Artisans at Work — Inside Surat Textile Loom",
      autoplay: false,
      muted: true,
      loop: false,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { paddingY: "py-4" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  ICON: {
    type: "ICON",
    name: "Icon Badge",
    category: "content",
    categoryName: "Content & Typography",
    description: "Custom SVG/Lucide badge with accompanying label and tooltip",
    iconName: "Sparkles",
    defaultSettings: {
      icon: "ShieldCheck",
      title: "100% Genuine Handloom Mark",
      subtitle: "Government of India Silk Mark Certified",
      size: "lg",
    },
    defaultStyle: { paddingY: "py-2", accentColor: "#1455D9" },
    defaultResponsive: { desktop: { alignment: "left" }, mobile: { alignment: "center" } },
    defaultDataSource: { type: "STATIC" },
  },
  BUTTON: {
    type: "BUTTON",
    name: "Action Button CTA",
    category: "content",
    categoryName: "Content & Typography",
    description: "Standalone CTA button with custom gradient, size, icon & link",
    iconName: "MousePointerClick",
    defaultSettings: {
      label: "Explore Festive Collection →",
      targetUrl: "/shop",
      variant: "gradient",
      size: "lg",
      icon: "ArrowRight",
    },
    defaultStyle: { paddingY: "py-2", accentColor: "#1455D9" },
    defaultResponsive: { desktop: { alignment: "left" }, mobile: { alignment: "center" } },
    defaultDataSource: { type: "STATIC" },
  },
  HTML_BLOCK: {
    type: "HTML_BLOCK",
    name: "HTML-Safe Content Block",
    category: "content",
    categoryName: "Content & Typography",
    description: "Sanitized custom HTML/CSS embed for third-party badges or tracking pixels",
    iconName: "Code",
    defaultSettings: {
      htmlContent: "<div class='p-4 bg-amber-500/10 border border-amber-500/30 rounded-2xl text-center text-xs font-bold text-amber-500'>⚡ Festival Special: Free Shipping On All Prepaid Orders!</div>",
    },
    defaultStyle: { paddingY: "py-2" },
    defaultResponsive: { desktop: { paddingY: "py-2" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },

  // ==========================================
  // 2. E-COMMERCE WIDGETS (13)
  // ==========================================
  PRODUCT_GRID: {
    type: "PRODUCT_GRID",
    name: "Product Grid",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Multi-column responsive grid displaying products with ratings, badges & add-to-cart",
    iconName: "Grid",
    defaultSettings: {
      title: "Handpicked Indian Products",
      subtitle: "Top rated across ethnic wear, audio gadgets & essentials",
      columns: 4,
      limit: 8,
      showViewAll: true,
      viewAllUrl: "/shop",
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { columns: 4 }, tablet: { columns: 3 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "all", limit: 8 },
  },
  PRODUCT_CAROUSEL: {
    type: "PRODUCT_CAROUSEL",
    name: "Product Carousel",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Horizontal scrolling product reel with smooth touch gestures & arrows",
    iconName: "Sliders",
    defaultSettings: {
      title: "Popular This Week",
      subtitle: "Swipe to browse trending selections",
      limit: 8,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "trending", limit: 8 },
  },
  PRODUCT_SLIDER: {
    type: "PRODUCT_SLIDER",
    name: "Product Slider",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Full-width featured product spotlight slider with quick variant selector",
    iconName: "Layers",
    defaultSettings: {
      title: "Deal of the Hour Spotlight",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { paddingY: "py-6" }, mobile: { paddingY: "py-4" } },
    defaultDataSource: { type: "PRODUCTS", filter: "featured", limit: 4 },
  },
  PRODUCT_CARD: {
    type: "PRODUCT_CARD",
    name: "Single Product Card",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Standalone high-impact hero product card with quick buy & pricing details",
    iconName: "Box",
    defaultSettings: {
      productSlug: "fancyhub-pro-anc-earbuds",
      highlightBadge: "SUPER SAVER",
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { paddingY: "py-4" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "PRODUCTS", filter: "featured", limit: 1 },
  },
  FLASH_DEALS: {
    type: "FLASH_DEALS",
    name: "Flash Deals Countdown",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "High-urgency promotional block with ticking timer & steep discount tags",
    iconName: "Zap",
    defaultSettings: {
      title: "Live Flash Deals of the Day",
      subtitle: "Special limited-time discounts expiring soon",
      badge: "FLAT 50% OFF",
      hoursRemaining: 14,
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "flash_deals", limit: 4 },
  },
  BEST_SELLERS: {
    type: "BEST_SELLERS",
    name: "Best Sellers Showcase",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Top-ranked marketplace products with rank badges #1–#5",
    iconName: "Award",
    defaultSettings: {
      title: "Marketplace Best Sellers",
      subtitle: "The most purchased items by 50,000+ shoppers this month",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "best_sellers", limit: 4 },
  },
  NEW_ARRIVALS: {
    type: "NEW_ARRIVALS",
    name: "New Arrivals Reel",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Latest artisan drops, newly listed mobile accessories & festive releases",
    iconName: "Sparkles",
    defaultSettings: {
      title: "Just Landed — New Arrivals",
      subtitle: "Fresh collections straight from the loom and tech studio",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "new_arrivals", limit: 4 },
  },
  FEATURED_PRODUCTS: {
    type: "FEATURED_PRODUCTS",
    name: "Featured Products",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Editor's curated picks with premium styling and verified artisan tags",
    iconName: "Star",
    defaultSettings: {
      title: "Editor's Handpicked Picks",
      subtitle: "Curated for exceptional craftsmanship and authenticity",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "featured", limit: 4 },
  },
  TRENDING_PRODUCTS: {
    type: "TRENDING_PRODUCTS",
    name: "Trending Products",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Products with rising weekly views, social shares and positive ratings",
    iconName: "TrendingUp",
    defaultSettings: {
      title: "Trending in India Right Now",
      subtitle: "Viral styles and hot tech gadgets",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "trending", limit: 4 },
  },
  RECENTLY_VIEWED: {
    type: "RECENTLY_VIEWED",
    name: "Recently Viewed Carousel",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Personalized history shelf of products browsed in the current session",
    iconName: "Clock",
    defaultSettings: {
      title: "Pick Up Where You Left Off",
      subtitle: "Your recently viewed items",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "all", limit: 4 },
  },
  RECOMMENDED_PRODUCTS: {
    type: "RECOMMENDED_PRODUCTS",
    name: "Recommended Products",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "AI-driven personalized recommendations based on category interest",
    iconName: "HeartHandshake",
    defaultSettings: {
      title: "Recommended For You",
      subtitle: "Tailored to your style and regional tastes",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "trending", limit: 4 },
  },
  DEALS: {
    type: "DEALS",
    name: "Deals & Discount Grid",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Special bargain zone for items with discounts >= 30%",
    iconName: "Percent",
    defaultSettings: {
      title: "Mega Value Deals Under ₹1,999",
      subtitle: "Unbeatable budget pricing directly from manufacturers",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "flash_deals", limit: 4 },
  },
  WISHLIST_PRODUCTS: {
    type: "WISHLIST_PRODUCTS",
    name: "Wishlist Quick Teaser",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Customer saved wishlist items with instant move-to-cart buttons",
    iconName: "Heart",
    defaultSettings: {
      title: "Your Saved Favourites",
      subtitle: "Items waiting in your wishlist",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", filter: "all", limit: 4 },
  },
  GROUP_BUYING: {
    type: "GROUP_BUYING",
    name: "Social Group Buying & Bulk Wholesale",
    category: "ecommerce",
    categoryName: "E-commerce & Products",
    description: "Group buying deals with tiered wholesale pricing, 2-hour countdown timers, and WhatsApp viral invites",
    iconName: "Users",
    defaultSettings: {
      title: "Buy Together & Save Up to 35%",
      subtitle: "Invite friends on WhatsApp to unlock direct-from-weaver wholesale prices with delivery to separate addresses.",
      limit: 3,
      categoryFilter: "ALL",
      showTimer: true,
    },
    defaultStyle: { paddingY: "py-8" },
    defaultResponsive: { desktop: { columns: 3 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "STATIC" },
  },

  // ==========================================
  // 3. CATEGORY WIDGETS (5)
  // ==========================================
  CATEGORY_GRID: {
    type: "CATEGORY_GRID",
    name: "Category Grid",
    category: "category",
    categoryName: "Category Navigation",
    description: "Visual category blocks with high-res photography and subcategory links",
    iconName: "Grid",
    defaultSettings: {
      title: "Explore Departments",
      columns: 4,
      limit: 8,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "CATEGORIES", limit: 8 },
  },
  CATEGORY_CAROUSEL: {
    type: "CATEGORY_CAROUSEL",
    name: "Circular Category Strip",
    category: "category",
    categoryName: "Category Navigation",
    description: "Circular avatar icon bar for frictionless 1-tap mobile category filtering",
    iconName: "Compass",
    defaultSettings: {
      style: "circular",
      limit: 8,
    },
    defaultStyle: { paddingY: "py-3" },
    defaultResponsive: { desktop: { columns: 8 }, mobile: { columns: 4 } },
    defaultDataSource: { type: "CATEGORIES", limit: 8 },
  },
  CATEGORY_CARDS: {
    type: "CATEGORY_CARDS",
    name: "Category Cards",
    category: "category",
    categoryName: "Category Navigation",
    description: "Cards showing category images, product count, and starting prices",
    iconName: "CreditCard",
    defaultSettings: {
      title: "Popular Categories",
      columns: 3,
      limit: 6,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 3 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "CATEGORIES", limit: 6 },
  },
  FEATURED_CATEGORIES: {
    type: "FEATURED_CATEGORIES",
    name: "Featured Categories Banner",
    category: "category",
    categoryName: "Category Navigation",
    description: "Hero multi-banner highlighting flagship departments like Sarees & Mobile Tech",
    iconName: "Tag",
    defaultSettings: {
      title: "Curated Departments",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 2 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "CATEGORIES", limit: 4 },
  },
  MEGA_CATEGORY_MENU: {
    type: "MEGA_CATEGORY_MENU",
    name: "Mega Category Menu",
    category: "category",
    categoryName: "Category Navigation",
    description: "Hierarchical multi-column category breakdown with subcategories",
    iconName: "Menu",
    defaultSettings: {
      title: "Complete Category Directory",
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "CATEGORIES" },
  },

  // ==========================================
  // 4. VENDOR WIDGETS (5)
  // ==========================================
  VENDOR_GRID: {
    type: "VENDOR_GRID",
    name: "Vendor Grid",
    category: "vendor",
    categoryName: "Vendor & Sellers",
    description: "Grid showcasing verified master weavers, artisans, and certified brand hubs",
    iconName: "Store",
    defaultSettings: {
      title: "Verified Indian Weavers & Artisans",
      subtitle: "Shop directly from genuine textile hubs with zero middlemen markup",
      columns: 4,
      limit: 4,
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "VENDORS", limit: 4 },
  },
  TOP_VENDORS: {
    type: "TOP_VENDORS",
    name: "Top Rated Vendors",
    category: "vendor",
    categoryName: "Vendor & Sellers",
    description: "Top-rated sellers with verified star badges, follower counts & store links",
    iconName: "Medal",
    defaultSettings: {
      title: "Top Rated Master Weavers",
      limit: 3,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 3 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "VENDORS", limit: 3 },
  },
  FEATURED_VENDORS: {
    type: "FEATURED_VENDORS",
    name: "Featured Vendor Spotlight",
    category: "vendor",
    categoryName: "Vendor & Sellers",
    description: "Hero brand spotlight showcasing a master weaver's story & products",
    iconName: "Crown",
    defaultSettings: {
      vendorSlug: "surat-silk-mills",
      title: "Weaver of the Month: Surat Silk Mills",
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { paddingY: "py-6" }, mobile: { paddingY: "py-4" } },
    defaultDataSource: { type: "VENDORS", limit: 1 },
  },
  VENDOR_STORE_CARD: {
    type: "VENDOR_STORE_CARD",
    name: "Vendor Store Card",
    category: "vendor",
    categoryName: "Vendor & Sellers",
    description: "Compact store card with banner, logo, city & product count",
    iconName: "BadgeCheck",
    defaultSettings: {
      title: "Featured Store",
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 2 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "VENDORS", limit: 2 },
  },
  VENDOR_PRODUCTS: {
    type: "VENDOR_PRODUCTS",
    name: "Vendor Products Showcase",
    category: "vendor",
    categoryName: "Vendor & Sellers",
    description: "Product catalog reel belonging exclusively to a selected seller",
    iconName: "ShoppingBag",
    defaultSettings: {
      vendorName: "Kanchipuram Heritage Looms",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "PRODUCTS", limit: 4 },
  },

  // ==========================================
  // 5. MARKETING WIDGETS (9)
  // ==========================================
  HERO_BANNER: {
    type: "HERO_BANNER",
    name: "Hero Banner Carousel",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Multi-slide hero promotional carousel with responsive typography, badges & CTAs",
    iconName: "Presentation",
    defaultSettings: {
      slides: [
        {
          badge: "FESTIVE DHAMAKA 2026",
          title: "Pure Banarasi & Kanchipuram Silk Sarees",
          subtitle: "Directly from master weavers of Varanasi & Surat. Up to 60% OFF.",
          ctaText: "Shop Handloom Drop",
          ctaLink: "/shop",
          imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1600&auto=format&fit=crop&q=80",
        },
      ],
      autoplay: true,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { paddingY: "py-4" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  PROMO_BANNER: {
    type: "PROMO_BANNER",
    name: "Promo Banners Grid",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Multi-column promotional banner cards for marketing campaigns & drops",
    iconName: "LayoutTemplate",
    defaultSettings: {
      columns: 2,
      banners: [
        {
          badge: "NEW LAUNCH",
          title: "ANC Audio & Earbuds",
          subtitle: "Starting ₹1,499",
          ctaText: "Explore Audio",
          ctaLink: "/deals",
          imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
        },
        {
          badge: "EXCLUSIVE",
          title: "Custom Print Studio",
          subtitle: "T-Shirts & Hoodies",
          ctaText: "Design Now",
          ctaLink: "/custom-print",
          imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
        },
      ],
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 2 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "STATIC" },
  },
  COUPON_BANNER: {
    type: "COUPON_BANNER",
    name: "Coupon Reward Banner",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Interactive discount voucher cards with one-click copy code functionality",
    iconName: "Ticket",
    defaultSettings: {
      title: "Exclusive Discount Coupons",
      subtitle: "Apply at checkout for instant savings",
      coupons: [
        { code: "FANCYFIRST", discount: "FLAT ₹200 OFF", minOrder: "₹999", badge: "NEW USER" },
        { code: "UPIFANCY", discount: "EXTRA 10% CASHBACK", minOrder: "₹1,499", badge: "PREPAID" },
      ],
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 2 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "STATIC" },
  },
  COUNTDOWN_TIMER: {
    type: "COUNTDOWN_TIMER",
    name: "Countdown Timer Banner",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Urgency countdown clock for sales with hours, minutes and seconds",
    iconName: "Timer",
    defaultSettings: {
      title: "Diwali Mega Dhamaka Ends In:",
      hours: 18,
      minutes: 45,
      ctaText: "Grab Deal Now",
      ctaLink: "/deals",
    },
    defaultStyle: { paddingY: "py-4", backgroundColor: "#0A1128" },
    defaultResponsive: { desktop: { alignment: "center" }, mobile: { alignment: "center" } },
    defaultDataSource: { type: "STATIC" },
  },
  ANNOUNCEMENT_BAR: {
    type: "ANNOUNCEMENT_BAR",
    name: "Announcement Ribbon Ticker",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Live marquee ribbon notification for free shipping, sales & offers",
    iconName: "Megaphone",
    defaultSettings: {
      text: "⚡ FREE Express Delivery across India on all prepaid UPI orders! | Use Code: FANCYFIRST",
      badge: "LIVE OFFER",
      link: "/deals",
      speed: "normal",
    },
    defaultStyle: { paddingY: "py-2", backgroundColor: "#1455D9", textColor: "#FFFFFF" },
    defaultResponsive: { desktop: { paddingY: "py-2" }, mobile: { paddingY: "py-1.5" } },
    defaultDataSource: { type: "STATIC" },
  },
  OFFER_STRIP: {
    type: "OFFER_STRIP",
    name: "Offer Strip Bar",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Colored compact banner strip highlighting ongoing payment offers",
    iconName: "Tag",
    defaultSettings: {
      text: "🎉 Pay with RuPay / UPI & get Instant 5% Cashback on orders above ₹1,000",
      ctaText: "Learn More",
      ctaLink: "/help",
    },
    defaultStyle: { paddingY: "py-2.5", backgroundColor: "#F7941D", textColor: "#000000" },
    defaultResponsive: { desktop: { paddingY: "py-2.5" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  FESTIVAL_BANNER: {
    type: "FESTIVAL_BANNER",
    name: "Festive Season Spotlight",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Rich festive Indian gradient banner with artisanal saree / kurta showcase",
    iconName: "Sparkles",
    defaultSettings: {
      badge: "SURAT TEXTILE HUB DIRECT",
      title: "Pure Banarasi & Jacquard Silk Sarees Starting at ₹1,499",
      subtitle: "Zero middlemen commission. Get authentic artisanal sarees straight from verified master weavers.",
      ctaText: "Explore Saree Collection →",
      ctaLink: "/shop",
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { paddingY: "py-6" }, mobile: { paddingY: "py-4" } },
    defaultDataSource: { type: "STATIC" },
  },
  NEWSLETTER: {
    type: "NEWSLETTER",
    name: "Newsletter & Instant Coupon",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Email subscription box with instant discount coupon code generator",
    iconName: "Mail",
    defaultSettings: {
      title: "Join India's Fastest Growing Marketplace Club",
      subtitle: "Get ₹500 instant wallet credits on sign-up, exclusive handloom drops & weekend flash coupons.",
      buttonText: "Claim ₹500 Reward",
      instantCouponCode: "FANCYVIP500",
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { paddingY: "py-6" }, mobile: { paddingY: "py-4" } },
    defaultDataSource: { type: "STATIC" },
  },
  CTA_BANNER: {
    type: "CTA_BANNER",
    name: "Dual Button CTA Banner",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Call to action banner with dual primary and secondary action buttons",
    iconName: "MousePointer",
    defaultSettings: {
      title: "Start Selling on FancyHub.in Today",
      subtitle: "Join 5,000+ Indian weavers, artisans & electronics innovators with zero onboarding fees.",
      primaryText: "Register as Seller",
      primaryLink: "/vendor/register",
      secondaryText: "Learn More",
      secondaryLink: "/help",
    },
    defaultStyle: { paddingY: "py-6", backgroundColor: "#0A1128" },
    defaultResponsive: { desktop: { paddingY: "py-6" }, mobile: { paddingY: "py-4" } },
    defaultDataSource: { type: "STATIC" },
  },
  SPIN_WHEEL: {
    type: "SPIN_WHEEL",
    name: "Festive Spin-the-Wheel",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Interactive lucky fortune wheel capturing WhatsApp leads and rewarding instant discount coupons",
    iconName: "Disc",
    defaultSettings: {
      title: "Diwali Festive Fortune Wheel",
      subtitle: "Enter your WhatsApp number to spin & win up to ₹500 discount vouchers!",
      buttonText: "Spin Now & Win",
      requirePhone: true,
      slices: [
        { label: "₹500 OFF", coupon: "DIWALI500", color: "#F59E0B" },
        { label: "Flat 15% OFF", coupon: "FESTIVE15", color: "#8B5CF6" },
        { label: "Free Delivery", coupon: "FREESHIP", color: "#10B981" },
        { label: "₹200 OFF", coupon: "FANCY200", color: "#EC4899" },
        { label: "10% Cashback", coupon: "CASHBACK10", color: "#3B82F6" },
        { label: "Try Again", coupon: "BETTERLUCK", color: "#64748B" },
      ],
    },
    defaultStyle: { paddingY: "py-8" },
    defaultResponsive: { desktop: { paddingY: "py-8" }, mobile: { paddingY: "py-6" } },
    defaultDataSource: { type: "STATIC" },
  },
  SCRATCH_CARD: {
    type: "SCRATCH_CARD",
    name: "Scratch & Win Voucher",
    category: "marketing",
    categoryName: "Marketing & Conversion",
    description: "Interactive scratch surface with percentage revealed counter and instant coupon unlock",
    iconName: "Gift",
    defaultSettings: {
      title: "Festive Scratch & Win",
      subtitle: "Scratch the golden card below with your finger or mouse to reveal your mystery gift!",
      rewardCoupon: "FESTIVESURPRISE",
      rewardDiscountText: "Flat ₹300 OFF + Free Express Shipping",
    },
    defaultStyle: { paddingY: "py-8" },
    defaultResponsive: { desktop: { paddingY: "py-8" }, mobile: { paddingY: "py-6" } },
    defaultDataSource: { type: "STATIC" },
  },

  // ==========================================
  // 6. TRUST WIDGETS (5)
  // ==========================================
  FAST_DELIVERY: {
    type: "FAST_DELIVERY",
    name: "Fast Delivery Assurance",
    category: "trust",
    categoryName: "Trust & Assurance",
    description: "Express delivery badge with 2-4 day pan-India logistics details",
    iconName: "Truck",
    defaultSettings: {
      title: "Pan-India Express Delivery",
      subtitle: "Dispatched within 24 hours via Delhivery & BlueDart",
    },
    defaultStyle: { paddingY: "py-3" },
    defaultResponsive: { desktop: { paddingY: "py-3" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  SECURE_PAYMENTS: {
    type: "SECURE_PAYMENTS",
    name: "Secure Payments Badge",
    category: "trust",
    categoryName: "Trust & Assurance",
    description: "Payment safety assurance showcasing UPI, RuPay, Visa, Mastercard & COD",
    iconName: "CreditCard",
    defaultSettings: {
      title: "100% Secure & Encrypted Payments",
      subtitle: "RBI & PCI-DSS Compliant 256-Bit SSL Razorpay Gateway",
    },
    defaultStyle: { paddingY: "py-3" },
    defaultResponsive: { desktop: { paddingY: "py-3" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  TRUSTED_VENDORS: {
    type: "TRUSTED_VENDORS",
    name: "Trusted Vendors Guarantee",
    category: "trust",
    categoryName: "Trust & Assurance",
    description: "Artisan verification guarantee with GST & Silk Mark authentication",
    iconName: "ShieldCheck",
    defaultSettings: {
      title: "100% Verified Indian Artisans",
      subtitle: "Every seller is personally KYC-verified and factory-audited",
    },
    defaultStyle: { paddingY: "py-3" },
    defaultResponsive: { desktop: { paddingY: "py-3" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  EASY_RETURNS: {
    type: "EASY_RETURNS",
    name: "Easy Returns Assurance",
    category: "trust",
    categoryName: "Trust & Assurance",
    description: "7-day doorstep return and instant refund policy card",
    iconName: "RotateCcw",
    defaultSettings: {
      title: "7-Day Hassle-Free Returns",
      subtitle: "Doorstep pickup & instant refund into FancyHub Wallet or UPI",
    },
    defaultStyle: { paddingY: "py-3" },
    defaultResponsive: { desktop: { paddingY: "py-3" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  TRUST_BADGES: {
    type: "TRUST_BADGES",
    name: "Trust Assurance Badges (4-Pillar)",
    category: "trust",
    categoryName: "Trust & Assurance",
    description: "Complete 4-pillar trust grid (Free Shipping, COD, 7-Day Returns, Verified Sellers)",
    iconName: "Shield",
    defaultSettings: {
      columns: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "STATIC" },
  },

  // ==========================================
  // 7. SOCIAL & CONTENT WIDGETS (6)
  // ==========================================
  BLOG_POSTS: {
    type: "BLOG_POSTS",
    name: "Artisan Blog & Stories",
    category: "social",
    categoryName: "Social & Reviews",
    description: "Editorial blog cards sharing handloom weaving traditions & buying guides",
    iconName: "BookOpen",
    defaultSettings: {
      title: "Stories from Indian Looms",
      subtitle: "Discover the heritage, art and master weavers behind your clothes",
      limit: 3,
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { columns: 3 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "STATIC" },
  },
  TESTIMONIALS: {
    type: "TESTIMONIALS",
    name: "Customer Testimonials",
    category: "social",
    categoryName: "Social & Reviews",
    description: "Verified customer reviews carousel with star ratings and verified buyer badges",
    iconName: "MessageCircle",
    defaultSettings: {
      title: "Loved by 50,000+ Indian Shoppers",
      subtitle: "Real reviews from verified buyers across Delhi, Mumbai, Bengaluru & more",
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { columns: 3 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "STATIC" },
  },
  FAQ: {
    type: "FAQ",
    name: "FAQ Accordion",
    category: "social",
    categoryName: "Social & Reviews",
    description: "Expandable questions and answers accordion for customer support",
    iconName: "HelpCircle",
    defaultSettings: {
      title: "Frequently Asked Questions",
      subtitle: "Everything you need to know about ordering, delivery & returns",
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { paddingY: "py-6" }, mobile: { paddingY: "py-4" } },
    defaultDataSource: { type: "STATIC" },
  },
  REVIEWS: {
    type: "REVIEWS",
    name: "Product Reviews Showcase",
    category: "social",
    categoryName: "Social & Reviews",
    description: "Detailed photo reviews with star ratings and user avatars",
    iconName: "StarHalf",
    defaultSettings: {
      title: "Recent Buyer Feedback",
      limit: 4,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 2 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "STATIC" },
  },
  INSTAGRAM_GALLERY: {
    type: "INSTAGRAM_GALLERY",
    name: "Instagram Social Gallery",
    category: "social",
    categoryName: "Social & Reviews",
    description: "Visual social photo grid tagged with #FancyHubStyle from real customers",
    iconName: "Instagram",
    defaultSettings: {
      title: "Style with #FancyHub",
      subtitle: "Tag @fancyhub.in on Instagram to get featured on our homepage",
      limit: 6,
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { columns: 6 }, mobile: { columns: 3 } },
    defaultDataSource: { type: "STATIC" },
  },
  SHOPPABLE_REELS: {
    type: "SHOPPABLE_REELS",
    name: "Shoppable Video Reels",
    category: "social",
    categoryName: "Social & Reviews",
    description: "Vertical (9:16) video commerce reels with interactive product tag overlays and 1-tap cart checkout",
    iconName: "Video",
    defaultSettings: {
      title: "Watch & Shop Live Reels",
      subtitle: "See real master weavers in action and unbox trending gadgets",
      autoPlay: false,
      showProductPill: true,
      limit: 6,
      categoryFilter: "ALL",
    },
    defaultStyle: { paddingY: "py-8" },
    defaultResponsive: { desktop: { columns: 4 }, mobile: { columns: 2 } },
    defaultDataSource: { type: "STATIC" },
  },
  LIVE_VIDEO_COMMERCE: {
    type: "LIVE_VIDEO_COMMERCE",
    name: "Live Video Commerce Banner",
    category: "social",
    categoryName: "Social & Reviews",
    description: "Featured live artisan broadcast with real-time viewer count and instant buying drawer",
    iconName: "Radio",
    defaultSettings: {
      title: "Live Artisan Stream",
      isLive: true,
      viewerCount: 1420,
    },
    defaultStyle: { paddingY: "py-6" },
    defaultResponsive: { desktop: { columns: 1 }, mobile: { columns: 1 } },
    defaultDataSource: { type: "STATIC" },
  },
  BRAND_LOGOS: {
    type: "BRAND_LOGOS",
    name: "Partner Brand Logos",
    category: "social",
    categoryName: "Social & Reviews",
    description: "Scrolling brand logo carousel showing certified weaving guilds and tech partners",
    iconName: "Sparkle",
    defaultSettings: {
      title: "Certified Partner Guilds & Brands",
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { columns: 6 }, mobile: { columns: 3 } },
    defaultDataSource: { type: "STATIC" },
  },

  // ==========================================
  // 8. UTILITY WIDGETS (10)
  // ==========================================
  SEARCH: {
    type: "SEARCH",
    name: "Search Bar Widget",
    category: "utility",
    categoryName: "Utility & Navigation",
    description: "Interactive search input with category dropdown and instant search shortcut",
    iconName: "Search",
    defaultSettings: {
      placeholder: "Search for Sarees, Kurtas, Mobiles, ANC Earbuds, Brands...",
    },
    defaultStyle: { paddingY: "py-2" },
    defaultResponsive: { desktop: { paddingY: "py-2" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  BREADCRUMBS: {
    type: "BREADCRUMBS",
    name: "Breadcrumb Trail",
    category: "utility",
    categoryName: "Utility & Navigation",
    description: "Dynamic breadcrumb navigation path (Home → Menswear → Men's Shirts)",
    iconName: "ChevronsRight",
    defaultSettings: {
      rootLabel: "Home",
    },
    defaultStyle: { paddingY: "py-1.5" },
    defaultResponsive: { desktop: { paddingY: "py-1.5" }, mobile: { paddingY: "py-1" } },
    defaultDataSource: { type: "STATIC" },
  },
  PAGINATION: {
    type: "PAGINATION",
    name: "Pagination Controls",
    category: "utility",
    categoryName: "Utility & Navigation",
    description: "Numbered page selector for long catalog listings",
    iconName: "MoreHorizontal",
    defaultSettings: {
      currentPage: 1,
      totalPages: 12,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { paddingY: "py-4" }, mobile: { paddingY: "py-3" } },
    defaultDataSource: { type: "STATIC" },
  },
  FILTERS: {
    type: "FILTERS",
    name: "Product Filters Sidebar",
    category: "utility",
    categoryName: "Utility & Navigation",
    description: "Price slider, category checkboxes, rating filters and discount pills",
    iconName: "Filter",
    defaultSettings: {
      showPriceFilter: true,
      showCategoryFilter: true,
      showRatingFilter: true,
    },
    defaultStyle: { paddingY: "py-4" },
    defaultResponsive: { desktop: { paddingY: "py-4" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  SORT: {
    type: "SORT",
    name: "Sort Dropdown Selector",
    category: "utility",
    categoryName: "Utility & Navigation",
    description: "Sorting selector (Popularity, Price: Low to High, High to Low, Rating, Newest)",
    iconName: "ArrowUpDown",
    defaultSettings: {
      defaultSort: "popularity",
    },
    defaultStyle: { paddingY: "py-2" },
    defaultResponsive: { desktop: { paddingY: "py-2" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  RECENTLY_VIEWED_UTILITY: {
    type: "RECENTLY_VIEWED_UTILITY",
    name: "Recently Viewed Tray",
    category: "utility",
    categoryName: "Utility & Navigation",
    description: "Compact floating recent history tray",
    iconName: "History",
    defaultSettings: {
      title: "Recently Viewed",
      limit: 3,
    },
    defaultStyle: { paddingY: "py-2" },
    defaultResponsive: { desktop: { paddingY: "py-2" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  COMPARE_TRAY: {
    type: "COMPARE_TRAY",
    name: "Product Compare Tray",
    category: "utility",
    categoryName: "Utility & Navigation",
    description: "Comparison tray for side-by-side product specifications & pricing",
    iconName: "Columns",
    defaultSettings: {
      title: "Compare Products (Max 4)",
    },
    defaultStyle: { paddingY: "py-2" },
    defaultResponsive: { desktop: { paddingY: "py-2" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  WISHLIST_BUTTON: {
    type: "WISHLIST_BUTTON",
    name: "Wishlist Quick Button",
    category: "utility",
    categoryName: "Utility & Navigation",
    description: "Heart bookmark button with active count indicator",
    iconName: "Heart",
    defaultSettings: {
      label: "My Wishlist",
    },
    defaultStyle: { paddingY: "py-2" },
    defaultResponsive: { desktop: { paddingY: "py-2" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  CART_SUMMARY: {
    type: "CART_SUMMARY",
    name: "Cart Summary Drawer Teaser",
    category: "utility",
    categoryName: "Utility & Navigation",
    description: "Subtotal, items count & checkout teaser block",
    iconName: "ShoppingBag",
    defaultSettings: {
      title: "Your Shopping Bag",
    },
    defaultStyle: { paddingY: "py-3" },
    defaultResponsive: { desktop: { paddingY: "py-3" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
  ACCOUNT_SUMMARY: {
    type: "ACCOUNT_SUMMARY",
    name: "Account & Wallet Summary",
    category: "utility",
    categoryName: "Utility & Navigation",
    description: "Customer profile avatar, wallet credits balance and orders status banner",
    iconName: "User",
    defaultSettings: {
      title: "Welcome back, Shopper!",
    },
    defaultStyle: { paddingY: "py-3" },
    defaultResponsive: { desktop: { paddingY: "py-3" }, mobile: { paddingY: "py-2" } },
    defaultDataSource: { type: "STATIC" },
  },
};
